---
title: "Stroke Analysis"
output: 
  html_document:
    theme: flatly
    code_folding: hide
    df_print: kable
---

```{r include = FALSE}
# Load libraries & set plot theme
library(here)
library(ggpol)
library(tsibble)
library(feasts)
library(fable)
library(fabletools)
library(tidyverse)
```

```{r include = FALSE}
# Set custom theme for plots
theme_strokes <- function() {
  theme_classic() %+replace%
    theme(
      plot.title.position = "plot",
      strip.background = element_blank(), 
      strip.text = element_text(face="bold"),
      axis.title = element_blank(),
      axis.line = element_blank(),
      axis.ticks.y = element_blank(),
      plot.title=element_text(face = "bold", 
                              size = rel(1.2),
                              margin = margin(0, 0, 5, 5)
    ))
}

theme_set(theme_strokes())
```

```{r include = FALSE}
# Read in cleaned stroke data
activity_hb <- read_csv(here("data/clean/activity_hb.csv")) %>%
  filter(admission_type == "All")
activity_ca <- read_csv(here("data/clean/activity_ca.csv")) %>%
  filter(admission_type == "All")
mortality_hb <- read_csv(here("data/clean/mortality_hb.csv"))
mortality_ca <- read_csv(here("data/clean/mortality_ca.csv"))
```

```{r include = FALSE}
# Read in cleaned population data
pop_total_hb <- read_csv(here("data/clean/population_total_hb.csv"))
pop_ages_hb <- read_csv(here("data/clean/population_ages_hb.csv"))
pop_total_ca <- read_csv(here("data/clean/population_total_ca.csv"))
pop_ages_ca <- read_csv(here("data/clean/population_ages_ca.csv"))
```



```{r include = FALSE}
# Summary of total number of stroke discharges by type
activity_hb %>%
  filter(hb_name == "Scotland" &
           admission_type == "All" &
           age_group == "All" &
           sex == "All" &
           year == 2018) %>%
  group_by(diagnosis, sex, age_group) %>%
  summarise(discharges = sum(number_of_discharges))
```

```{r include = FALSE}
# Summary of total number of stroke deaths by type
mortality_hb %>%
  filter(hb_name == "Scotland" &
           age_group == "All" &
           sex == "All" &
           year == 2018) %>%
  group_by(year, sex, diagnosis) %>%
  summarise(total_deaths = sum(number_of_deaths))
```

```{r echo = FALSE}
# Total discharges split by diagnosis, 2018
activity_hb %>%
  filter(hb_name == "Scotland" 
         & age_group == "All"
         & sex == "All"
         & year == "2018") %>%
  group_by(diagnosis) %>%
  summarise(discharges = sum(number_of_discharges)) %>%
  ggplot() +
  aes(
    x = reorder(diagnosis, discharges),
    y = discharges
  ) +
  geom_col(fill = "violetred4") +
  geom_text(aes(label = discharges, hjust = -0.2)) +
  labs(title = "Total number of discharges (2018)") +
  scale_y_continuous(
    labels = scales::comma,
    limits = c(0, 40000)
  ) +
  coord_flip()

ggsave("discharges_sco_2018.png", path = here("outputs"))
```

```{r}
# Total deathss split by diagnosis, 2018
mortality_hb %>%
  filter(hb_name == "Scotland" &
    age_group == "All" &
    sex == "All" &
    year == "2018") %>%
  group_by(diagnosis) %>%
  summarise(deaths = sum(number_of_deaths)) %>%
  ggplot() +
  aes(
    x = reorder(diagnosis, deaths),
    y = deaths
  ) +
  geom_col(fill = "violetred4") +
  geom_text(aes(label = deaths, hjust = -0.2)) +
  labs(title = "Total number of deaths (2018)") +
  scale_y_continuous(
    labels = scales::comma,
    limits = c(0, 4500)
  ) +
  coord_flip()

ggsave("deaths_sco_2018.png", path = here("outputs"))
```

```{r}
# Total discharges by sex, diagnosis, age_group
activity_hb %>%
  filter(hb_name == "Scotland" 
         & !age_group %in% c("All", "under75 years")
         & sex != "All"
         & year == "2018") %>%
  group_by(diagnosis, sex, age_group) %>%
  summarise(discharges = sum(number_of_discharges)) %>%
  ggplot() +
  aes(
    x = age_group,
    y = discharges,
    fill = sex
  ) +
  geom_col(position = "dodge") +
  theme(
    legend.position = "bottom",
    legend.title = element_blank()
  ) +
  labs(title = "Total number of discharges (2018)") +
  scale_y_continuous(labels = scales::comma) +
  scale_fill_manual(
    values = c(
      "Male" = "darkblue",
      "Female" = "skyblue"
    )
  ) +
  theme(
    axis.title = element_blank(),
    axis.line = element_blank(),
    panel.grid.major.x = element_line(linetype = "solid")
  ) +
  coord_flip() +
  facet_wrap(~diagnosis)

ggsave("discharges_diagn_2018.png", path = here("outputs"))
```

```{r}
# Total deaths by sex, diagnosis, age_group
mortality_hb %>%
  filter(hb_name == "Scotland" 
         & !age_group %in% c("All", "under75 years") 
         & sex != "All" 
         & year == "2018") %>%
  group_by(diagnosis, sex, age_group) %>%
  summarise(deaths = sum(number_of_deaths)) %>%
  ggplot() +
  aes(
    x = age_group,
    y = deaths,
    fill = sex
  ) +
  geom_col(position = "dodge") +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    panel.grid.major.x = element_line(linetype = "solid")
  ) +
  labs(title = "Total number of deaths (2018)") +
  scale_y_continuous(labels = scales::comma) +
  scale_fill_manual(
    values = c(
      "Male" = "darkblue",
      "Female" = "skyblue"
    )
  ) +
  coord_flip() +
  facet_wrap(~ diagnosis, ncol = 2)

ggsave("deaths_diagn_2018.png", path = here("outputs"))
```


```{r}
pop_ages_hb %>%
  filter(year == 2018 &
    sex != "All" &
    hb_name == "Scotland") %>%
  group_by(sex, age_band1) %>%
  summarise(total_pop = sum(count)) %>%
  ggplot(aes(
    x = age_band1,
    fill = sex,
    y = ifelse(test = sex == "Male",
      yes = -total_pop,
      no = total_pop
    )
  )) +
  geom_bar(stat = "identity") +
  theme(
    panel.grid.major.x = element_line(linetype = "solid"),
    legend.position = "bottom",
    legend.title = element_blank()
  ) +
  labs(title = "Scottish population (estimated, 2018)") +
  scale_fill_manual(values = c("Male" = "darkblue", "Female" = "skyblue")) +
  scale_y_continuous(
    breaks = c(
      -200000, -150000, -100000, -50000, 0,
      50000, 100000, 150000, 200000
    ),
    labels = c(
      "200k", "150k", "100k", "50k", "0",
      "50k", "100k", "150k", "200k"
    )
  ) +
  guides(fill = guide_legend(reverse = TRUE)) +
  coord_flip()

ggsave("pop_pyramid2018.png", path = here("outputs"))
```

```{r}
# Mortality rates
mortality_hb %>%
  filter(hb_name == "Scotland" &
    !age_group %in% c("All", "under75 years") &
    sex != "All" &
    year == "2018") %>%
  ggplot(aes(
    x = age_group,
    y = easr,
    colour = sex
  )) +
  geom_point(
    fill = "white",
    size = 4,
    alpha = 0.8
  ) +
  coord_flip() +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    panel.grid.major.x = element_line(linetype = "solid")
  ) +
  scale_colour_manual(values = c("Male" = "darkblue", "Female" = "skyblue")) +
  labs(
    title = "Mortality Rates (2018)",
    caption = "deaths per 100,000, age standardised to European Standard Population"
  ) +
  facet_wrap(~diagnosis, scales = "free_y", ncol = 2)

ggsave("mort_easr_2018.png", path = here("outputs"))
```


```{r}
# Health board population
pop_total_hb %>%
  filter(year == 2018 &
    sex == "All" &
    age == "all_ages" &
    hb_name != "Scotland") %>%
  group_by(hb_name) %>%
  summarise(total_pop = sum(count)) %>%
  ggplot(aes(
    x = reorder(hb_name, total_pop),
    y = total_pop
  )) +
  labs(title = "Health board populations (2018)") +
  theme(panel.grid.major.x = element_line(linetype = "solid")) +
  scale_y_continuous(
    labels = scales::comma,
    limits = c(0, 1300000)
  ) +
  geom_col(fill = "violetred4") +
  coord_flip()

ggsave("hb_populations.png", path = here("outputs"))
```


```{r}
# Health Board comparison

mortality_hb %>%
  filter(age_group == "75plus years" &
    sex == "All" &
    year == "2018" &
    diagnosis == "Stroke") %>%
  ggplot(aes(
    x = reorder(hb_name, easr),
    y = easr,
    group = hb_name
  )) +
  geom_point(
    size = 3,
    colour = "violetred4"
  ) +
  geom_segment(aes(
    x = reorder(hb_name, easr),
    xend = reorder(hb_name, easr),
    y = 0,
    yend = easr
  ),
  linetype = "dashed",
  size = 0.1
  ) +
  scale_y_continuous(limits = c(0,500)) +
  labs(
    title = "Stroke mortality rates, age 75+ (2018)",
    caption = "deaths per 100,000, age standardised to European Standard Population"
  ) +
  coord_flip()

ggsave("hbcomp_easr_2018.png", path = here("outputs"))
```

```{r}
highlight_mort <- mortality_hb %>%
  filter(year == "2018"
         & age_group == "75plus years" &
    sex == "All" &
    diagnosis == "Stroke")

mortality_hb %>%
  filter(age_group == "75plus years" &
    sex == "All" &
    diagnosis == "Stroke") %>%
  ggplot(aes(
    x = reorder(hb_name, easr),
    y = easr,
    group = hb_name
  )) +
    geom_point(
    size = 3,
    shape = 1,
    alpha = 0.3
  )  +
   geom_point(data = highlight_mort,
    size = 3,
    colour = "violetred4"
  ) +
  theme(panel.grid.major.y = element_line(linetype = "solid")) +
  scale_y_continuous(limits = c(0, NA)) +
  labs(
    title = "Stroke mortality rates, age 75+ (2009 - 2018)",
    caption = "deaths per 100,000, age standardised to European Standard Population
    Filled point is 2018 rate"
  ) +
  coord_flip()

ggsave("hbcomp_easr_all.png", path = here("outputs"))
```

```{r}
mortality_ca %>%
  filter(age_group == "75plus years" &
    sex == "All" &
    year == "2018" &
    diagnosis == "Stroke") %>%
  ggplot(aes(
    x = reorder(hb_name, easr),
    y = easr
  )) +
  geom_point(size = 3,
             colour = "violetred4") +
  theme(
    panel.grid.major.y = element_line(linetype = "solid"),
    legend.position = "none",
  ) +
  scale_y_continuous(
    labels = scales::comma,
    limits = c(0, 600)
  ) +
  labs(
    title = "Stroke mortality rates, age 75+ (2018)",
    caption = "deaths per 100,000, age standardised to European Standard Population
    Points show rates for the councils which make up each health board"
  ) +
  coord_flip()

ggsave("hbcouncil_easr_2018l.png", path = here("outputs"))
```

```{r}
# Health Board comparison
mortality_ca %>%
  filter(age_group == "75plus years" &
    sex == "All" &
    year == "2018" &
    diagnosis == "Stroke" &
    hb_name == "NHS Greater Glasgow and Clyde") %>%
  ggplot(aes(
    x = reorder(ca_name, easr),
    y = easr,
    group = ca_name
  )) +
  geom_point(
    size = 3,
    colour = "violetred4"
  ) +
  geom_segment(aes(
    x = reorder(ca_name, easr),
    xend = reorder(ca_name, easr),
    y = 0,
    yend = easr
  ),
  linetype = "dashed",
  size = 0.1
  ) +
  scale_y_continuous(limits = c(0,500)) +
  labs(
    title = "Stroke mortality rates, age 75+ (2018)",
    caption = "deaths per 100,000, age standardised to European Standard Population"
  ) +
  coord_flip()

ggsave("glasgow_easr_2018.png", path = here("outputs"))
```

```{r}
highlight_ca <- mortality_ca %>%
  filter(year == "2018" 
         & age_group == "75plus years" &
    sex == "All" &
    year == "2018" &
    diagnosis == "Stroke" &
    hb_name == "NHS Greater Glasgow and Clyde")


mortality_ca %>%
  filter(age_group == "75plus years" &
    sex == "All" &
    diagnosis == "Stroke" &
    hb_name == "NHS Greater Glasgow and Clyde") %>%
  ggplot(aes(
    x = reorder(ca_name, easr),
    y = easr,
    group = ca_name
  )) +
  geom_point(
    size = 3,
    shape = 1,
    alpha = 0.3
  ) +
    geom_point(data = highlight_ca,
    size = 3,
    colour = "violetred4"
  ) +
  theme(panel.grid.major.y = element_line(linetype = "solid")) +
  scale_y_continuous(limits = c(0, NA)) +
  labs(
    title = "Stroke mortality rates, age 75+ (2009 - 2018)",
    caption = "deaths per 100,000, age standardised to European Standard Population
    Filled point is 2018 rate"
  ) +
  coord_flip()

ggsave("glasgow_easr_all.png", path = here("outputs"))
```

Forecasting work - rates

```{r}
#Make Scotland activoty data into a tsibble
activity_ts_sco <- activity_hb %>% 
  filter(hb_name == "Scotland" 
         & sex != "All"
         & !age_group %in% c("under75 years", "All")
         & diagnosis == "Stroke")

activity_ts_sco <- as_tsibble(activity_ts_sco, key = c(age_group, sex), index = year)
```

```{r}
# Plot rates over time
activity_ts_sco %>% 
  ggplot() +
  aes(x = year,
      y = easr,
      colour = sex) +
  geom_line() +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    axis.line.y = element_line(),
    panel.grid.major.y = element_line(linetype = "solid")
  ) +
  scale_colour_manual(values = c("Male" = "darkblue", "Female" = "skyblue")) +
  labs(
    title = "Stroke Discharge Rates (2009 - 2018)",
    caption = "discharges per 100,000,age standardised to European Standard Population"
  ) +
  facet_wrap(~ age_group, scales = "free")

ggsave("discharge_easr_all.png", path = here("outputs"))
```

```{r}
# Make Scotland mortality data into a tsibble
mortality_ts_sco <- mortality_hb %>% 
  filter(hb_name == "Scotland" 
         & sex != "All"
         & !age_group %in% c("under75 years", "All")
         & diagnosis == "Stroke")

mortality_ts_sco <- as_tsibble(mortality_ts_sco, key = c(age_group, sex), index = year)
```

```{r}
# Plot rates over time
mortality_ts_sco %>% 
  ggplot() +
  aes(x = year,
      y = easr,
      colour = sex) +
  geom_line() +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    axis.line.y = element_line(),
    panel.grid.major.y = element_line(linetype = "solid")
  ) +
  scale_colour_manual(values = c("Male" = "darkblue", "Female" = "skyblue")) +
  labs(
    title = "Stroke Mortality Rates (2009 - 2018)",
    caption = "discharges per 100,000, age standardised to European Standard Population"
  ) +
  facet_wrap(~ age_group, scales = "free")

ggsave("mort_easr_all.png", path = here("outputs"))
```

```{r}
# Fit model to forecast mortality rates
fit <- mortality_ts_sco %>%
  filter(age_group == "75plus years") %>% 
  model(
   ets = ETS(easr),
   arima = ARIMA(easr)
   )

forecast_1 <- fit %>%
  forecast(h = 20)
```

```{r}
forecast_1 %>%
  autoplot(mortality_ts_sco) +
  ggtitle("Forecasts of standardised stroke mortality rates (age 75+)") +
  theme(axis.line.y = element_line(),
        panel.grid.major.y = element_line(linetype = "solid")) +
  facet_grid(~ sex)

ggsave("forecast_rate.png", path = here("outputs"))
```

Use population projection to forecast discharges/deaths

```{r}
# Get discharge rates for 2018
activity_scotland_rates_2018 <- activity_hb %>%
    filter(age_group != "under75 years"
           & sex != "All"
           & diagnosis == "Stroke"
           & admission_type == "All"
           & year == 2018
         ) %>% 
  select(hb_name, age_group, sex, crude_rate, easr) %>% 
  rename(crude_rate_act = crude_rate,
         easr_act = easr) 
```

```{r}
# Get historic number of discharges
activity_scotland_discharges <- activity_hb %>%
    filter(age_group != "under75 years"
           & sex != "All"
           & diagnosis == "Stroke"
           & admission_type == "All"
         ) %>% 
  select(hb_name, year, age_group, sex, number_of_discharges)
```


```{r}
# Get mortality rates for 2018
mortality_scotland_rates_2018 <- mortality_hb %>% 
  filter(age_group != "under75 years"
           & sex != "All"
           & diagnosis == "Stroke"
           & year == 2018) %>% 
  select(hb_name, age_group, sex, crude_rate, easr) %>% 
  rename(crude_rate_mort = crude_rate,
         easr_mort = easr)
```

```{r}
# Get historic number of deaths
mortality_scotland_deaths <- mortality_hb %>% 
  filter(age_group != "under75 years"
           & sex != "All"
           & diagnosis == "Stroke") %>% 
  select(hb_name, year, age_group, sex, number_of_deaths)
```


```{r}
# Population estimates/projections
# Filter out years for which stroke data is not available
population_scotland <- pop_ages_hb %>% 
  filter(sex != "All" & year >= 2009) %>% 
  group_by(hb_name, year, sex, age_band2) %>% 
  summarise(population = sum(count))

```

```{r}
# Add 2018 mortality/discharge rates 
population_scotland <- population_scotland %>% 
  left_join(mortality_scotland_rates_2018,
            by = c("hb_name",
                   "sex", 
                   "age_band2" = "age_group")) %>% 
  left_join(activity_scotland_rates_2018,
            by = c("hb_name",
                   "sex", 
                   "age_band2" = "age_group"))
```

```{r}
# Add number of deaths/discharges
# Will be blank for years > 2018
population_scotland <- population_scotland %>% 
  left_join(mortality_scotland_deaths,
            by = c("hb_name", 
                   "year",
                   "sex", 
                   "age_band2" = "age_group")) %>% 
  left_join(activity_scotland_discharges,
            by = c("hb_name", 
                   "year",
                   "sex", 
                   "age_band2" = "age_group"))
```


```{r}
# Use rates to get projected number of deaths/discharges
population_scotland <- population_scotland %>% 
  mutate(
    deaths_forecast = if_else(year <= 2018,
                              number_of_deaths,
                              population/100000 * easr_mort),
    cases_forecast = if_else(year <= 2018,
                             number_of_discharges,
                             population/100000 * easr_act),
    type = if_else(year <= 2018, 
                   "actual",
                   "projection")
  )
```

```{r}
# Plot population forecast
pop_forecast_ageband <- population_scotland %>%
  group_by(hb_name, year, age_band2,) %>% 
  summarise(pop_ageband = sum(population),
            deaths_ageband = sum(deaths_forecast),
            discharges_ageband = sum(cases_forecast)) 
```

```{r}
pop_forecasts <- population_scotland %>%
  group_by(hb_name, year) %>% 
  summarise(pop_total = sum(population),
            deaths_total = sum(deaths_forecast),
            discharges_total = sum(cases_forecast)) 
```

```{r}
pop_forecast_ageband <- pop_forecast_ageband%>% 
  left_join(pop_forecasts, by = c("hb_name", "year")) %>% 
  mutate(ageband_pct = pop_ageband/pop_total)
```

```{r}
pop_highlight <- pop_ages_hb %>%
  filter(sex != "All" 
         & hb_name == "Scotland"
         & year > 2018) %>% 
  group_by(year) %>%
  summarise(total_pop = sum(count)) 

pop_ages_hb %>%
  filter(sex != "All" 
         & hb_name == "Scotland"
         & year >= 2009
         & year <= 2018) %>%
  group_by(year) %>%
  summarise(total_pop = sum(count)) %>% 
  ggplot() +
  aes(x = year, y = total_pop) +
  geom_line(colour = "violetred4", size = 1.5) +
   geom_line(data = pop_highlight,
             colour = "violetred4", size = 1.5, linetype = "dotdash") +
   theme(
    panel.grid.major.y = element_line(linetype = "solid"),
    axis.line.y = element_line()
  ) +
  scale_y_continuous(limits = c(4000000, 6000000),
                     labels = scales::comma) +
  labs(title = "Population projection")

ggsave("forecast_pop.png", path = here("outputs"))
```




```{r}
pop_ages_hb %>%
  filter(year %in% c("1981", "2001", "2021", "2041")
         & sex != "All" 
         & hb_name == "Scotland") %>%
  group_by(year, sex, age_band1) %>%
  summarise(total_pop = sum(count)) %>%
  ggplot(aes(
    x = age_band1,
    fill = sex,
    y = ifelse(test = sex == "Male",
      yes = -total_pop,
      no = total_pop
    )
  )) +
  geom_bar(stat = "identity") +
  theme(
    panel.grid.major.x = element_line(linetype = "solid"),
    legend.position = "bottom",
    legend.title = element_blank()
    
  ) +
  labs(title = "Projected age structure of Scotland") +
  scale_fill_manual(values = c("Male" = "darkblue", "Female" = "skyblue")) +
  scale_y_continuous(
    breaks = c(
      -200000, -150000, -100000, -50000, 0,
      50000, 100000, 150000, 200000
    ),
    labels = c(
      "200k", "150k", "100k", "50k", "0",
      "50k", "100k", "150k", "200k"
    )
  ) +
  guides(fill = guide_legend(reverse = TRUE)) +
  coord_flip() +
  facet_wrap(~ year
             )

ggsave("forecast_pyramid.png", path = here("outputs"))
```

```{r}
pop_forecasts_highlight <- pop_forecasts %>% 
  filter(year > "2018" 
         & hb_name == "Scotland")

pop_forecasts %>% 
  filter(year <= "2018"
         & hb_name == "Scotland") %>% 
  ggplot() +
  aes(x = year, y = deaths_total) +
  geom_line(colour = "violetred4") +
  geom_line(data = pop_forecasts_highlight, linetype = "dotdash", colour = "violetred4") +
   theme(
    panel.grid.major.y = element_line(linetype = "solid"),
    axis.line.y = element_line()
  ) +
  scale_y_continuous(limits = c(0, 4000)) +
  labs(title = "Projection of stroke deaths") 

ggsave("forecast_deaths.png", path = here("outputs"))
```

```{r}
pop_forecasts %>% 
  filter(year <= "2018" 
         & hb_name == "Scotland") %>% 
  ggplot() +
  aes(x = year, y = discharges_total) + 
  geom_line(colour = "violetred4") +
  geom_line(data = pop_forecasts_highlight, linetype = "dotdash", colour = "violetred4") +
   theme(
    panel.grid.major.y = element_line(linetype = "solid"),
    axis.line.y = element_line()
  ) +
  
  scale_y_continuous(limits = c(10000, 40000)) +
  labs(title = "Projection of stroke discharges")

ggsave("forecast_discharges.png", path = here("outputs"))
```


