---
title: "Data manipulation script"
output: html_notebook
---

```{r}
library(janitor)
library(skimr)
library(tidyverse)
library(here)
```

```{r}
# Read in stroke source data
# Two sets of data: 
#  1. Hospital activity related to strokes
#  2. Stroke mortality data
# Both datasets are produced at Health Board (hb) and Council Area (ca)
# Columns ending 'qf' are codes relating to data quality and can be removed

activity_hb_raw <- read_csv(here("data/raw/stroke_activitybyhb.csv")) %>% 
  clean_names() %>% 
  select(-ends_with("qf"))
activity_ca_raw <- read_csv(here("data/raw/stroke_activitybyca.csv")) %>% 
  clean_names() %>% 
  select(-ends_with("qf"))
mortality_hb_raw <- read_csv(here("data/raw/stroke_mortalitybyhbr.csv")) %>% 
  clean_names() %>% 
  select(-ends_with("qf"))
mortalilty_ca_raw <- read_csv(here("data/raw/stroke_mortalitybyca.csv"))%>% 
  clean_names() %>% 
  select(-ends_with("qf"))
```

```{r}
# read in population estimates

population_hb_raw <- read_csv(here("data/raw/population_est_hb.csv")) %>% 
  clean_names() %>% 
  select(-ends_with("qf"))
population_ca_raw <- read_csv(here("data/raw/population_est_ca.csv"))%>% 
  clean_names() %>% 
  select(-ends_with("qf"))
```

```{r}
# read in population projections

population_proj_hb_raw <- read_csv(here("data/raw/population_proj_hb.csv")) %>% 
  clean_names() %>% 
  select(-ends_with("qf"))
population_proj_ca_raw <- read_csv(here("data/raw/population_proj_ca.csv")) %>% 
  clean_names() %>% 
  select(-ends_with("qf"))
```

```{r}
# read in Health Board/Council id lookups 
hb_id <- read_csv(here("data/clean/health_board_id.csv"))
ca_id <- read_csv(here("data/clean/council_id.csv"))
id_lookups <- read_csv(here("data/clean/id_lookups.csv"))
```


```{r}
# Manipulate activity data:

activity_ca <- activity_ca_raw %>% 
  left_join(ca_id, by = c("ca" = "la_code")) %>% 
  mutate(year = str_sub(financial_year, 1, 4),
         la_name = if_else(ca == "S92000003", "Scotland", la_name)
         ) %>% 
  select(-financial_year) %>% 
  relocate(year)

activity_hb <- activity_hb_raw %>% 
  left_join(hb_id, by = c("hbr" = "hb_code")) %>% 
  mutate(year = str_sub(financial_year, 1, 4),
         hb_name = if_else(hbr == "S92000003", "Scotland", hb_name)
         ) %>% 
  select(-financial_year) %>% 
  relocate(year)
  
```

